-- ======================================================================
-- Topic 43: Query Execution Plans (EXPLAIN)
-- ======================================================================

-- ------------------------------------------------------------
-- 📖 In Simple Words
-- ------------------------------------------------------------

-- * Definition: An execution plan (EXPLAIN) shows how the database will run your query: which tables it reads first, whether it uses an index or scans the whole table, and how many rows it expects.

-- * Real-life example: Google Maps showing the route before you drive.

-- * 🧩 Syntax:
--     EXPLAIN SELECT ...;
--     EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT | JSON) SELECT ...;   -- ANALYZE actually runs the query

-- * Syntax explained (each part):
--   - EXPLAIN → shows the plan without running the query
--   - ANALYZE → runs it and shows real time and row counts
--   - FORMAT → output style: table / tree / JSON
--   - Key fields → MySQL: type, key, rows, Extra. PostgreSQL: node type, cost, rows, actual time

-- * Example on salesdb (run 00-Setup-Sample-Data.sql first):
SET search_path TO sales;
EXPLAIN SELECT * FROM orders WHERE orderid = 5;
EXPLAIN SELECT * FROM orders WHERE sales > 20;

-- * Example explained (step by step):
--   1. The first plan uses the primary key (MySQL type = const / PostgreSQL may show Index Scan or Seq Scan on tiny tables) — it goes straight to one row.
--   2. The second plan has no index on sales, so it must scan all rows (type = ALL / Seq Scan).
--   3. Reading plans tells you where to add an index.

-- ------------------------------------------------------------
-- 43.1 What is an Execution Plan?
-- ------------------------------------------------------------

-- * Definition: An execution plan (also called a query plan or roadmap) is a detailed map generated by the database planner that shows exactly how it processes your query step-by-step.

-- * Uses: It is used to understand how the database retrieves data, which indexes it uses, what joins are performed, and how efficient your query is. It shows exactly where you might have performance issues.

-- * How it works in PostgreSQL:

--   1. Parser checks the SQL; the rewriter expands views.

--   2. The planner/optimizer builds possible plans and estimates their cost using table statistics (from `ANALYZE`, stored in `pg_statistic` / view `pg_stats`).

--   3. It chooses scan types (Seq Scan vs Index Scan vs Bitmap Scan) and join types (Nested Loop vs Hash Join vs Merge Join).

--   4. The executor runs the cheapest plan, reads pages (from `shared_buffers` or disk), joins them, and sends the result.

--   5. Caching: PostgreSQL does NOT cache plans for normal queries — each query is planned again. Prepared statements (and SQL inside PL/pgSQL functions) can reuse a plan within the same connection (after 5 runs PostgreSQL may switch to a "generic plan").

-- ------------------------------------------------------------
-- 43.2 Types of Execution Plans
-- ------------------------------------------------------------

-- * Diagram summary: Compares Estimated vs Actual vs Live execution plans

-- 1. Estimated Execution Plan (What PostgreSQL plans to do)

-- * Definition: The planner's prediction of how it will execute the query, without running it.

-- * Key Points:

--   * Query is NOT executed.

--   * Shows: scan type and index, join types, estimated rows (`rows=`), row width, and cost (`cost=startup..total`, in arbitrary units).

--   * Helps you preview performance before running a heavy query.

-- * Example:
EXPLAIN SELECT * FROM employees WHERE department = 'Sales';
--                          QUERY PLAN
-- -------------------------------------------------------------
--  Seq Scan on employees  (cost=0.00..18.50 rows=5 width=64)
--    Filter: ((department)::text = 'Sales'::text)

-- 2. Actual Execution Plan (What PostgreSQL really did)

-- * Definition: The real plan showing how the query actually executed, including real row counts, time taken, and runtime statistics.

-- * Key Points:

--   * Query IS executed. ⚠️ For `UPDATE`/`DELETE`, wrap it: `BEGIN; EXPLAIN ANALYZE UPDATE ...; ROLLBACK;`

--   * Shows `actual time=`, `rows=` (real), `loops=`, and with `BUFFERS` how many pages came from memory (`shared hit`) or disk (`read`).

-- * Example:
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM employees WHERE department = 'Sales';
--  Index Scan using idx_emp_dept on employees
--      (cost=0.29..8.31 rows=5 width=64) (actual time=0.020..0.025 rows=4 loops=1)
--    Index Cond: ((department)::text = 'Sales'::text)
--    Buffers: shared hit=3
--  Planning Time: 0.110 ms
--  Execution Time: 0.045 ms

-- 3. Live Execution Plan (with Live Statistics)

-- * Definition: Shows query execution in real-time (mainly in SQL Server Management Studio).

--   * ⚠️ PostgreSQL has no live plan view. Watch running queries with `SELECT pid, state, now() - query_start AS running_for, query FROM pg_stat_activity;`, progress of some operations in `pg_stat_progress_create_index`, `pg_stat_progress_vacuum`, `pg_stat_progress_copy`, and log slow plans automatically with the `auto_explain` module.

-- * Key Points:

--   * Used for long-running queries to identify bottlenecks while the query is executing.

--   * Shows live progress (% completion) and live row counts.

-- ------------------------------------------------------------
-- 43.2.1 🐘 How to Read a PostgreSQL Plan
-- ------------------------------------------------------------

-- * Read it from the most indented line (inside) to the top (outside). Each `->` is a step that feeds the step above it.

-- * Common nodes:

-- | Node | Meaning | Good / Bad |
-- | :--- | :--- | :--- |
-- | `Seq Scan` | Reads the whole table | Bad on big tables with selective filters; fine on small tables |
-- | `Index Scan` | Walks the index, then reads heap rows | Good for few rows |
-- | `Index Only Scan` | Answers from the index alone (`Heap Fetches: 0` is best) | Best |
-- | `Bitmap Index Scan` + `Bitmap Heap Scan` | Collects matching CTIDs, then reads pages in order | Good for medium number of rows |
-- | `Nested Loop` / `Hash Join` / `Merge Join` | Join algorithms (Topic 45) | Depends on sizes |
-- | `Sort` (`Sort Method: external merge Disk`) | Sorting spilled to disk | Increase `work_mem` or add an index |
-- | `HashAggregate` / `GroupAggregate` | `GROUP BY` | — |

-- * Red flags: estimated `rows=` very different from actual `rows=`, `Rows Removed by Filter` very large, `Seq Scan` on a big table, sorts on disk, `loops=` huge inside a Nested Loop.

-- ------------------------------------------------------------
-- 43.3 Estimated vs Actual Execution Plan Match
-- ------------------------------------------------------------

-- * If the estimated row counts do not match the actual ones, it indicates issues like stale statistics or skewed data, which can lead the planner to a bad plan.

-- * If the estimated and actual rows match, then your statistics are up-to-date.

--   * Clarification: A match only means the estimates were correct. The query can still be slow if the plan itself is bad (for example, a Seq Scan because an index is missing). In PostgreSQL, refresh statistics with `ANALYZE table_name;` (autovacuum also runs it). For correlated columns use extended statistics: `CREATE STATISTICS st_city_state (dependencies) ON city, state FROM customers;`

-- * Q1. How do you find why a query is slow?

--   * Answer: Find it with `pg_stat_statements` or `log_min_duration_statement`, then run `EXPLAIN (ANALYZE, BUFFERS)`; look for Seq Scans on big tables, wrong row estimates, sorts/hashes spilling to disk, and big `loops`.

-- * Q2. Which scan types are good and bad?

--   * Answer: For selective filters: `Index Only Scan` (best) → `Index Scan` → `Bitmap Heap Scan` → `Seq Scan` (worst on big tables). But a Seq Scan is the right choice when the query needs most of the table.

-- * Q3. What does "Sort Method: external merge Disk" or a big "Hash ... Batches" mean?

--   * Answer: The sort or hash did not fit in `work_mem` and spilled to disk. Add an index that gives the order, reduce rows earlier, or raise `work_mem` for that query (`SET work_mem = '64MB';`).

-- * Q4. Estimated rows are very different from actual rows — why?

--   * Answer: Stale statistics, skewed data, or correlated columns. Run `ANALYZE t;`, raise the statistics target (`ALTER TABLE t ALTER COLUMN col SET STATISTICS 1000;`), or create extended statistics (`CREATE STATISTICS`).

-- * Q5. How do you log slow queries?

--   * Answer: `ALTER SYSTEM SET log_min_duration_statement = '1s'; SELECT pg_reload_conf();` — queries slower than 1 s are written to the server log. For totals per query, enable the `pg_stat_statements` extension; for automatic plans, `auto_explain`.

-- ---

-- ======================================================================
-- 🎯 Practice Questions (salesdb sample data) — try first, then look at the answer
-- ======================================================================
-- Run 00-Setup-Sample-Data.sql once before this section.

SET search_path TO sales;

-- Q1. Read the plan of a join with GROUP BY.
EXPLAIN SELECT p.category, SUM(o.sales)
FROM orders o JOIN products p ON p.productid = o.productid
GROUP BY p.category;

-- Q2. Compare estimated vs actual rows.
EXPLAIN ANALYZE SELECT * FROM orders WHERE customerid = 3;

-- Q3. Plan in JSON format.
EXPLAIN (FORMAT JSON) SELECT * FROM customers WHERE country = 'USA';
