-- ======================================================================
-- Topic 43: Query Execution Plans (EXPLAIN)
-- ======================================================================

-- ------------------------------------------------------------
-- 📖 In Simple Words
-- ------------------------------------------------------------

-- * Definition: An execution plan (EXPLAIN) shows how the database will run your query: which tables it reads first, whether it uses an index or scans the whole table, and how many rows it expects.

-- * Real-life example: Google Maps showing the route before you drive.

-- * 🧩 Syntax:
--     EXPLAIN SELECT ...;
--     EXPLAIN FORMAT=TREE | JSON SELECT ...;
--     EXPLAIN ANALYZE SELECT ...;            -- actually runs the query

-- * Syntax explained (each part):
--   - EXPLAIN → shows the plan without running the query
--   - ANALYZE → runs it and shows real time and row counts
--   - FORMAT → output style: table / tree / JSON
--   - Key fields → MySQL: type, key, rows, Extra. PostgreSQL: node type, cost, rows, actual time

-- * Example on salesdb (run 00-Setup-Sample-Data.sql first):
USE salesdb;
EXPLAIN SELECT * FROM orders WHERE orderid = 5;
EXPLAIN SELECT * FROM orders WHERE sales > 20;

-- * Example explained (step by step):
--   1. The first plan uses the primary key (MySQL type = const / PostgreSQL may show Index Scan or Seq Scan on tiny tables) — it goes straight to one row.
--   2. The second plan has no index on sales, so it must scan all rows (type = ALL / Seq Scan).
--   3. Reading plans tells you where to add an index.

-- ------------------------------------------------------------
-- 43.1 What is an Execution Plan?
-- ------------------------------------------------------------

-- * Definition: An execution plan (also called a query plan or roadmap) is a detailed map or blueprint generated by the database engine that shows exactly how it processes your query step-by-step. 

-- * Uses: It is used to understand how the database retrieves data, which indexes it uses, what joins are performed, and how efficient your query is. It shows exactly where you might have performance issues.

-- * How it works: 

--   1. Before executing the query, the database plans how to execute it based on statistics (e.g., Scan index vs full table scan).

--   2. It decides which type of joins to use (e.g., hash join vs nested loop join).

--   3. Finally, it executes the `SELECT` statement.

--   4. Once ready, the database engine implements the steps, reads tables from disk, joins them, and sends the result.

--   5. Caching: The database engine stores this execution plan in the cache. If you run the exact same query again, it reuses the cached plan instantly instead of building it from scratch!

--      * ⚠️ Note: Plan caching is a SQL Server (and Oracle) feature. MySQL builds a new plan for every normal query; only prepared statements partly reuse their parsed form.

-- ------------------------------------------------------------
-- 43.2 Types of Execution Plans
-- ------------------------------------------------------------

-- * Diagram summary: Compares Estimated vs Actual vs Live execution plans

--   ┌ ASCII diagram
--   │  Estimated plan : before running  (EXPLAIN)          → guesses rows
--   │  Actual plan    : after running   (EXPLAIN ANALYZE)  → real rows + time
--   │  Live plan      : while running   (progress view)    → current progress
--   └

-- 1. Estimated Execution Plan (What MySQL plans to do)

-- * Definition: The optimizer’s prediction of how it plans to execute the query without actually running it.

-- * Key Points:

--   * Query is NOT executed.

--   * Shows the optimizer’s guess about: which indexes it will use, join types, estimated rows to read, and query cost.

--   * Helps you preview performance before running a heavy query.

-- * Example: `EXPLAIN SELECT * FROM employees WHERE department = 'Sales';`

-- 2. Actual Execution Plan (What MySQL really did)

-- * Definition: The real plan showing how the query actually executed, including real row counts, time taken, and runtime statistics.

-- * Key Points:

--   * Query IS executed.

--   * Shows what actually happened: real number of rows read, actual execution time per step, and whether the optimizer’s estimates were correct.

-- * Example: `EXPLAIN ANALYZE SELECT * FROM employees WHERE department = 'Sales';`

-- 3. Live Execution Plan (with Live Statistics)

-- * Definition: Shows query execution in real-time (mainly in tools like SQL Server Management Studio or MySQL Workbench 8+).

--   * ⚠️ Note: Live Query Statistics is a SQL Server Management Studio feature. MySQL Workbench shows a graphical Visual Explain (estimated plan), not live progress. In MySQL you can watch a running query with `SHOW PROCESSLIST;`.

-- * Key Points:

--   * Used for long-running queries to identify bottlenecks while the query is executing.

--   * Shows live progress (% completion) and live row counts.

-- ------------------------------------------------------------
-- 43.3 Estimated vs Actual Execution Plan Match
-- ------------------------------------------------------------

-- * If the prediction does not match the actual plan, it indicates issues like inaccurate statistics or outdated indexes leading to poor performance.

-- * If the estimated and actual execution plan match, then your statistics are up-to-date and performance is optimal.

--   * Clarification: A match only means the optimizer's estimates were correct. The query can still be slow if the plan itself is bad (for example, a full table scan because an index is missing). In MySQL, refresh statistics with `ANALYZE TABLE table_name;`.

-- * Q1. How do you find why a query is slow?

--   * Answer: Run `EXPLAIN` (plan), then `EXPLAIN ANALYZE` (real time per step); look at `type`, `key`, `rows`, `Extra`; also check the slow query log.

-- * **Q2. Which `type` values are good and bad?**

--   * Answer: Best to worst: `system/const` → `eq_ref` → `ref` → `range` → `index` (full index scan) → `ALL` (full table scan).

-- * Q3. What do 'Using filesort' and 'Using temporary' mean?

--   * Answer: MySQL must sort rows itself (no index gives the order) or build an internal temporary table (GROUP BY/DISTINCT/UNION). An index matching the ORDER BY/GROUP BY columns often removes them.

-- * Q4. Estimated rows are very different from actual rows — why?

--   * Answer: Stale statistics or skewed data. Run `ANALYZE TABLE t;` or create histograms (`ANALYZE TABLE t UPDATE HISTOGRAM ON col;`).

-- * Q5. How do you enable the slow query log?

--   * Answer: `SET GLOBAL slow_query_log = 1; SET GLOBAL long_query_time = 1;` — queries slower than 1 s are logged (`SHOW VARIABLES LIKE 'slow_query_log_file';`).

-- ---

-- ======================================================================
-- 🧪 Practice Examples (salesdb sample data)
-- ======================================================================
-- First run 00-Setup-Sample-Data.sql once. Then run these one by one (select a statement → execute).
USE salesdb;

-- Basic plan:
EXPLAIN SELECT * FROM orders WHERE orderid = 5;          -- type = const (primary key)
EXPLAIN SELECT * FROM orders WHERE customerid = 2;       -- type = ref (index on customerid)
EXPLAIN SELECT * FROM orders WHERE sales > 20;           -- type = ALL (no index on sales → full scan)

-- Join plan:
EXPLAIN
SELECT c.firstname, SUM(o.sales) AS total_sales
FROM customers c
JOIN orders o ON o.customerid = c.customerid
GROUP BY c.firstname
ORDER BY total_sales DESC;

-- Tree format and actual run time (MySQL 8.0.18+):
EXPLAIN FORMAT=TREE SELECT * FROM orders WHERE customerid = 2;
EXPLAIN ANALYZE    SELECT * FROM orders WHERE customerid = 2;

-- Fix the full scan with an index, compare, then remove it:
CREATE INDEX idx_orders_sales ON orders (sales);
EXPLAIN SELECT * FROM orders WHERE sales > 20;            -- now range (optimizer may still choose ALL on tiny tables)
DROP INDEX idx_orders_sales ON orders;

-- Refresh statistics:
ANALYZE TABLE orders;

-- ======================================================================
-- 🎯 Practice Questions (salesdb sample data) — try first, then look at the answer
-- ======================================================================
-- Run 00-Setup-Sample-Data.sql once before this section.

USE salesdb;

-- Q1. Read the plan of a join with GROUP BY.
EXPLAIN SELECT p.category, SUM(o.sales)
FROM orders o JOIN products p ON p.productid = o.productid
GROUP BY p.category;

-- Q2. Compare estimated vs actual rows.
EXPLAIN ANALYZE SELECT * FROM orders WHERE customerid = 3;

-- Q3. Plan in JSON format.
EXPLAIN FORMAT=JSON SELECT * FROM customers WHERE country = 'USA';
